### PR TITLE
Fixed gnome-terminal folder bug + added optional wildcard preferences setting

### PR DESCRIPTION
**Pull request by protostork**
1 small bug fix + one feature addition request, pursuant to our previous chat: 
1. Small bug fix: the gnome-terminal option right at the bottom of the main.py file wasn't working for me when selecting a file, since the check for 'terminal' option that strips out the file path wasn't triggered. It should now be working.

2. Added a preferences setting in manifest.json to allow toggling wildcard searches in basic file name tracker search and in locate. It is disabled by default, so the behaviour of the extension should be identical to its default unless the user changes it. If the option is set, however, it inserts * wildcards into spaces between tracker or locate search key words

It looks like a lot of changes in the full files diff below, but it's actually only a few lines that were added (but due to indentation, diff says the entire blocks have changed). 

Please let me know any feedback or suggestions.

### CODE REVIEW

**Comment by protostork** [comment]
I think I've kinda got the hang of github now (more or less) so please also feel free to add me as a contributor as kindly offered earlier and I will update the readme file some time to reflect the new features.

**Comment by dalanicolai** [comment]
Great work! I have invited you to become callaborator

**Comment by protostork** [comment]
Thanks Daniel!

**Comment by dalanicolai** [comment]
Thank you as well of course...

**Pull request merged**
