### PR TITLE
Fixed the keywords bug that wouldn't parse user-set preferences

### PR DESCRIPTION
**Pull request by protostork**
Have modified the main.py script to do 2 things:
1. Keywords set in the preferences are now followed by the main.py script (fetches user-set keywords via extension.preferences)
2. Have tweaked the 'home' variable to not hard-code the directory, but to grab the current location of the script, so that I could test the fork properly on my local system (which has a different install directory in ulauncher cache due to the fork). This should be upstream compatible.

Have tested locally and seems to work fine for me...

### CODE REVIEW

**Comment by protostork** [comment]
Sorry for the bunch of tiny merges - still trying to figure out how to use git properly... Any advice much appreciated :)

Have now tested for both tracker searches and for locate, which seem to work fine. DocFetcher I don't have installed, but the change should work there also...

**Comment by dalanicolai** [comment]
Haha, no problem. Actually I am far from git expert myself, it is all new for me too. I am also not a software developer. Therefore I reviewed even the unnecessary commits. But eventually I figured out you did  a great job and I merged th fix with the main branch. Thank you for the fix. If one day you are interested to become collaborator or take over the maintainance then let me know. But otherwise for me it is okay like this also.

**Comment by dalanicolai** [comment]
I am not sure if you are using a lot the deep file search functionality of gnome-tracker. But my friend had some issues with gnome-tracker not finding parts of texts. We figured out we had to make some changes for tracker in the dconf-editor. Namely 1. We increased the max-words-to-index under tracker/fts & 2. we had to increase max-bytes under tracker/extract. Could save you some time if you encounter similar issues one day...

**Comment by protostork** [comment]
Thanks Daniel! Will let you know, for now until I get comfortable with git, if it works for you, I feel safer doing pushes to the fork rather than accidentally mangling the main repo :)

I haven't used deep search at all actually but will bear in mind when I try it out!

**Pull request merged**
