### PR TITLE
Allow customising text editor, file browser from preferences 

### PR DESCRIPTION
**Pull request by protostork**
Just a small feature addition to allow changing the default file manager and text editor from nautilus and gedit from the preferences. Shouldn't change the basic functionality and config at all, but for people who use something other than gedit or nautilus it could be useful (though sadly some file managers like spacefm, don't work properly with the full path with filename).

Was thinking about using 'xdg-mime query default text/text' to get the system default of the text editor, for instance, but I thought this could be faster, and easier for users to configure.

### CODE REVIEW

**Comment by desigit** [comment]
Also added a small bugfix so that the gnome-terminal option actually triggers os.path.dirname(os.path.abspath(data)) 

(before it checked for 'terminal' as the option string, not 'gnome-terminal', so it didn't get triggered, I think)

**Comment by protostork** [comment]
Sorry about the messy push requests - am having a hard time keeping my local customisations separate from the main branch ;)

gnome-terminal right now doesn't open in the right folder for some reason - I think it may be some issue with 'gnome-terminal --working-directory', not sure. Will investigate and maybe do a separate request if I can figure it out.

**Comment by dalanicolai** [comment]
Nice work! I guess these extra options have to be added to the manifest.json file also

**Comment by protostork** [comment]
Thanks! Yes, I'd added the 2 options to manifest.json, which seemed to work ok.

**Comment by dalanicolai** [comment]
Nice... however the option menu does not seem to work now... but I will investigate a little more

**Comment by dalanicolai** [comment]
> Thanks! Yes, I'd added the 2 options to manifest.json, which seemed to work ok.

Ah... somehow I did not see it... when reviewing the commit... have to learn a little more still

**Comment by dalanicolai** [comment]
> Nice... however the option menu does not seem to work now... but I will investigate a little more

Okay... it started to work again after I restarted ulauncher. So it seems everything is working alright. Thanks!

**Comment by protostork** [comment]
Cool, super! :)

**Pull request merged**
